services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Gateway/Dockerfile

  cart:
    image: ${DOCKER_REGISTRY-}cart
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: Cart.Api/Dockerfile

  product:
    image: ${DOCKER_REGISTRY-}product
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8082:8080"
    build:
      context: .
      dockerfile: Product.Api/Dockerfile


  productpostgres:
    image: postgres:latest
    environment:
        - POSTGRES_DB=productdb
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=pass
    ports:
        - "5433:5432"

  postgres:
    image: postgres:latest
    environment:
        - POSTGRES_DB=cartdb
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=pass
    ports:
        - "5432:5432"
